language: cpp
matrix:
  include:
  - compiler: gcc
  - compiler: clang
    env: QMAKESPEC=linux-clang

before_install:
- sudo add-apt-repository "deb http://cz.archive.ubuntu.com/ubuntu utopic main"
- sudo apt-get update
- sudo apt-get install qt5-default qt5-qmake qtbase5-dev-tools qtchooser qttools5-dev qtbase5-dev libgles2-mesa-dev libqt5gui5 libqt5serialport5-dev libqt5printsupport5 libqt5widgets5 libgles2-mesa libgl1-mesa-dev libgl1-mesa-glx libglapi-mesa libegl1-mesa-dev libpango-1.0-0
- sudo apt-get install zlib1g-dev libudev-dev cppcheck 
- git submodule update --init --recursive
- qmake -v
- sudo pip install packthing
script:
- qmake
- make -j4
- packthing -j4 --refresh deb
after_script:
- cppcheck --enable=all -q `git ls-files *.cpp`
- ls build/staging/
deploy:
  provider: releases
  api_key:
    secure: pXTKmYwykeSD1FSVFvkfR4q91X9AVkNPS2/FKDs+CnWDgFJyDrxsD8D596fLKA3OwbLD7QkXTBj4alhmj7OmcIf56ZZXlKy/O47OfC4JgHjkWYGIbE6CR/UpLRnGS251/zs8NjypnLSk+puiw1lHUqeIBqYGGCzkBN19uaGiyUc=
  file_glob: true
  file: build/staging/propelleride-*.deb
  skip_cleanup: true
  on:
    repo: parallaxinc/PropellerIDE
    tags: true
    all_branches: true
